# Generated by Django 6.0.7 on 2026-07-29 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('blood', 'Blood Test'), ('urine', 'Urine Test'), ('imaging', 'Imaging / X-Ray'), ('cardiac', 'Cardiac'), ('allergy', 'Allergy Test'), ('general', 'General Health')], default='general', max_length=50)),
                ('preparation_instructions', models.TextField(blank=True, help_text='Fasting, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('preferred_time', models.CharField(blank=True, help_text='e.g. Morning, Afternoon', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Home collection address')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('sample_collected', 'Sample Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_bookings', to=settings.AUTH_USER_MODEL)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.labtest')),
            ],
        ),
    ]
